name: wuzzuf_scraper
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.3.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  html: ^0.15.4

dev_dependencies:
  lints: 3.0.0
  test: ^1.25.5
